apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-server
        image: diqmwl/docversion
        ports:
        - containerPort: 1111
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: ingress-nginx
spec:
  selector:
    app: spring
  ports:
    - port: 9000
      targetPort: 1111
