apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: spring-server
        image: diqmwl/docversion
        ports:
        - containerPort: 1111
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    type: app
  ports:
    - port: 9000
      targetPort: 1111
